name: Run pylint-odoo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pylint-odoo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint-odoo

    - name: Run pylint-odoo
      run: |
        pylint-odoo custom-addons

    - name: Upload pylint-odoo report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pylint-odoo-report
        path: |
          .pylint-odoo
          .pylint-odoo.log
